-- Security for invites. The table, with row-level security already enabled,
-- comes from 20261002175516_waitlist_and_invites.sql, generated by Drizzle.
-- The waitlist's new columns need nothing here: 20260922233500's grants and
-- policy cover the whole table, so only staff read them. As in that file,
-- grants and policies are hand-written, never generated.

-- ─────────────────────────── Grants ───────────────────────────

-- Signed-out visitors get nothing. Someone opening a link never reads this
-- table from the browser: Get started looks the link up by its hash through
-- the server, on the owner connection, and every write goes through an action.
revoke all on public.invites from anon, authenticated;
--> statement-breakpoint

grant select on public.invites to authenticated;
--> statement-breakpoint

-- ─────────────────────────── Policies ───────────────────────────

-- Staff only. An invite belongs to someone who isn't a member yet, and holds
-- only the hash of the link, so no member ever needs to read it.
create policy "Staff read invites"
  on public.invites for select to authenticated
  using ((select private.is_staff()));
