-- Housemate security: helper functions, grants, row-level security policies,
-- realtime, and integrity triggers. Tables (with row-level security already
-- enabled) come from 20260915205225_init_schema.sql, generated by Drizzle.

-- ─── Helpers ────────────────────────────────────────────────────────────────
-- Kept in a schema the Data API doesn't expose.
create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated;

-- Homes the signed-in user belongs to as an active member. security definer
-- lets policies on public.members call it without recursing into themselves.
create or replace function private.current_home_ids()
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select m.home_id
  from public.members m
  where m.user_id = (select auth.uid())
    and m.status = 'active'
    and m.home_id is not null
$$;

create or replace function private.is_staff()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.members m
    where m.user_id = (select auth.uid())
      and m.role = 'staff'
      and m.status = 'active'
  )
$$;

revoke all on function private.current_home_ids() from public;
revoke all on function private.is_staff() from public;
grant execute on function private.current_home_ids() to authenticated;
grant execute on function private.is_staff() to authenticated;

-- ─── Grants ─────────────────────────────────────────────────────────────────
-- Browsers never write. Every write goes through server-side actions, which
-- connect as the database owner. Signed-in users may read; policies below
-- narrow which rows. Signed-out visitors get nothing.
revoke all on all tables in schema public from anon, authenticated;
grant select on
  public.homes,
  public.members,
  public.conversations,
  public.messages,
  public.activity_events,
  public.usage_costs,
  public.alerts
to authenticated;

-- Hosted projects expose new tables by default; match local config instead.
alter default privileges for role postgres in schema public
  revoke all on tables from anon, authenticated;

-- ─── Row-level security policies ────────────────────────────────────────────
create policy "Members read their own home"
  on public.homes for select to authenticated
  using (
    id in (select private.current_home_ids())
    or (select private.is_staff())
  );

create policy "Members read people in their home"
  on public.members for select to authenticated
  using (
    user_id = (select auth.uid())
    or home_id in (select private.current_home_ids())
    or (select private.is_staff())
  );

create policy "Members read their home's conversations"
  on public.conversations for select to authenticated
  using (
    home_id in (select private.current_home_ids())
    or (select private.is_staff())
  );

-- Texts from numbers that aren't invited have no home, so only staff see them.
create policy "Members read their home's messages"
  on public.messages for select to authenticated
  using (
    home_id in (select private.current_home_ids())
    or (select private.is_staff())
  );

create policy "Members read their home's activity"
  on public.activity_events for select to authenticated
  using (
    home_id in (select private.current_home_ids())
    or (select private.is_staff())
  );

create policy "Staff read usage costs"
  on public.usage_costs for select to authenticated
  using ((select private.is_staff()));

create policy "Staff read alerts"
  on public.alerts for select to authenticated
  using ((select private.is_staff()));

-- ─── Realtime ───────────────────────────────────────────────────────────────
-- The web app receives new messages and conversation changes live. Realtime
-- applies the policies above.
alter publication supabase_realtime add table public.messages, public.conversations;

-- ─── Activity log is append-only ────────────────────────────────────────────
-- Enforced by trigger, so it holds even for the server's own connection.
create or replace function private.reject_activity_event_change()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception 'activity_events is append-only'
    using errcode = 'insufficient_privilege';
end;
$$;

revoke all on function private.reject_activity_event_change() from public;

create trigger activity_events_append_only
  before update or delete on public.activity_events
  for each row execute function private.reject_activity_event_change();

create trigger activity_events_no_truncate
  before truncate on public.activity_events
  for each statement execute function private.reject_activity_event_change();

-- ─── Pilot member cap (D-029) ───────────────────────────────────────────────
-- Invited and active members count toward the cap; removed members and staff
-- don't.
create or replace function private.enforce_member_cap()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.role = 'member' and new.status in ('invited', 'active') then
    -- Serialise concurrent invites so two can't both take the last place.
    perform pg_advisory_xact_lock(hashtext('housemate.member_cap'));
    if (
      select count(*)
      from public.members m
      where m.role = 'member'
        and m.status in ('invited', 'active')
        and m.id <> new.id
    ) >= 10 then
      raise exception 'The pilot is limited to 10 members'
        using errcode = 'check_violation';
    end if;
  end if;
  return new;
end;
$$;

revoke all on function private.enforce_member_cap() from public;

create trigger members_cap
  before insert or update of role, status on public.members
  for each row execute function private.enforce_member_cap();
