-- Security for waitlist_signups. The table, with row-level security already
-- enabled, comes from 20260922233413_waitlist_signups.sql, generated by
-- Drizzle. This file follows 20260915205227_security.sql: grants and policies
-- are hand-written, never generated.

-- ─────────────────────────── Grants ───────────────────────────

-- Signed-out visitors get nothing, which is already the default: the base
-- security migration revokes everything from anon and sets default privileges
-- to revoke on new tables. Stated here anyway, because this is the one table a
-- signed-out stranger causes a write to, and silence would read as an
-- oversight rather than a decision. The write itself goes through the
-- joinWaitlist action on the owner connection, not from the browser.
revoke all on public.waitlist_signups from anon, authenticated;
--> statement-breakpoint

grant select on public.waitlist_signups to authenticated;
--> statement-breakpoint

-- ─────────────────────────── Policies ───────────────────────────

-- Staff only. A waitlist address belongs to someone who isn't a member yet and
-- has no home, so there is no member who should ever read this table.
create policy "Staff read waitlist signups"
  on public.waitlist_signups for select to authenticated
  using ((select private.is_staff()));
